### ISSUE TITLE
File Browser for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/filebrowser-startos#42]
### Service: Filebrowser
This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched.

**Current Status:**
- [x] Works Fine
- [ ] Partial Issues
- [ ] Doesn't Work

**Description:**
Filebrowser needs to be tested in StartOS 0.3.6 to ensure it functions as expected. The current observations are:
- Basic functionality appears to work.

**Tasks:**
- [ ] Perform in-depth testing on Filebrowser.
- [x] Investigate and resolve any health check issues.
- [ ] Confirm full compatibility with StartOS 0.3.6.
